version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: False
      DB_NAME: core_prod_rybm
      DB_USER: mu
      DB_PASSWORD: 6xW4062rQutrZhgsCIMWv15FBfmoC5DA
      DB_HOST: dpg-cubtcmhopnds73ai1l10-a.oregon-postgres.render.com
      DB_PORT: 5432
      SECRET_KEY: django-insecure-@pjglh-z1$)e)$t10myjf%rqwp%zr=c0=af_#70ddoskn@c(qv
    command: python manage.py runserver 0.0.0.0:8000
