# Generated by Django 5.1.5 on 2025-01-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='reservation_deposit',
            field=models.IntegerField(default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='unit',
            name='price',
            field=models.IntegerField(max_length=12),
        ),
    ]
