# Generated by Django 5.1.5 on 2025-01-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_unit_reservation_deposit_alter_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='reservation_deposit',
            field=models.IntegerField(default=0),
        ),
    ]
