# Generated by Django 5.1.5 on 2025-01-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_unit_price_alter_unit_reservation_deposit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='client',
            new_name='customer',
        ),
    ]
